=== clelaure/NEWREPO/XMLSpy/factureXPATHCSS.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2011 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="ST_surface">
		<xs:restriction base="xs:integer"/>
	</xs:simpleType>
	<xs:element name="ville" type="xs:string"/>
	<xs:element name="surface">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="ST_surface">
					<xs:attribute name="unite" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="m2"/>
								<xs:enumeration value="m3"/>
								<xs:enumeration value="m"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="ref" type="xs:string"/>
	<xs:element name="phtByUnit" type="xs:decimal"/>
	<xs:element name="nbUnit">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="typeUnit" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="lignes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ligne" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ligne">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ref"/>
				<xs:element ref="designation"/>
				<xs:element ref="surface" minOccurs="0"/>
				<xs:element ref="phtByUnit"/>
				<xs:element ref="nbUnit"/>
				<xs:element name="stotligne" type="xs:float" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="factures">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="facture" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="villeets" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="dateeditionXML" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:date"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="logourl" use="required"/>
			<xs:attribute name="rsets" type="xs:string" use="required"/>
			<xs:attribute name="cpets" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="5"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="adr2ets" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="adr1ets" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="facture">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="client" minOccurs="0"/>
				<xs:element ref="lignes"/>
			</xs:sequence>
			<xs:attribute name="type" type="xs:string" use="required"/>
			<xs:attribute name="numfacture" type="xs:integer" use="required"/>
			<xs:attribute name="refdevis" type="xs:integer" use="optional"/>
			<xs:attribute name="idclient" type="xs:short" use="required"/>
			<xs:attribute name="datefacture" type="xs:date" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="destinataire" type="xs:string"/>
	<xs:element name="designation" type="xs:string"/>
	<xs:element name="cp" type="xs:string"/>
	<xs:element name="client">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="destinataire"/>
				<xs:element ref="adr1"/>
				<xs:element ref="adr2"/>
				<xs:element ref="cp"/>
				<xs:element ref="ville"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="adr2">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="adr1">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== clelaure/NEWREPO/XMLSpy/Facture3.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="toExcel.xslt"?>
<factures rsets="ECO-nome" adr1ets="AV PIERRE GEORGES" adr2ets="" logourl="1.jpg" cpets="75015" villeets="Paris" dateeditionXML="2012-12-15" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="factureXPATHCSS.xsd">
	<facture numfacture="12" datefacture="2012-08-10" type="Devis" idclient="123">
		<client>
			<destinataire>jean rostremer</destinataire>
			<adr1>chemin de l'homme dormant</adr1>
			<adr2/>
			<cp>54230</cp>
			<ville>Nancy Lest</ville>
		</client>
		<lignes>
			<ligne>
				<ref>REF-2134</ref>
				<designation>Lavage SOL </designation>
				<phtByUnit>5.95</phtByUnit>
				<nbUnit typeUnit="HOUR">1.5</nbUnit>
				<stotligne>8.922</stotligne>
			</ligne>
			<ligne>
				<ref>REF-2135</ref>
				<designation>Peinture SOL forfait &lt;20m² </designation>
				<phtByUnit>8.95</phtByUnit>
				<nbUnit typeUnit="UNIT">1.5</nbUnit>
				<stotligne>13.425</stotligne>
			</ligne>
			<ligne>
				<ref>REF-1934</ref>
				<designation>Peinture Blanc pot 5L</designation>
				<phtByUnit>9.95</phtByUnit>
				<nbUnit typeUnit="UNIT">2</nbUnit>
				<stotligne>19.90</stotligne>
			</ligne>
		</lignes>
	</facture>
	<facture numfacture="23" datefacture="2012-09-04" type="Facture" idclient="234">
		<lignes>
			<ligne>
				<ref>REF-2234</ref>
				<designation>Pose BA13 (forfait plaque +MO) au m2 </designation>
				<surface unite="m2">15</surface>
				<phtByUnit>9.95</phtByUnit>
				<nbUnit typeUnit="HOURBYMETER2">0.5</nbUnit>
				<stotligne>74.625</stotligne>
			</ligne>
		</lignes>
	</facture>
	<facture numfacture="11" refdevis="08" datefacture="2012-07-05" type="Facture" idclient="234">
		<lignes>
			<ligne>
				<ref>REF-2234</ref>
				<designation>Pose BA13 (forfait plaque +MO) au m2 </designation>
				<surface unite="m2">5</surface>
				<phtByUnit>9.95</phtByUnit>
				<nbUnit typeUnit="HOURBYMETER2">0.5</nbUnit>
				<stotligne>24.873</stotligne>
			</ligne>
		</lignes>
	</facture>
	<facture numfacture="08" datefacture="2013-07-04" type="devis" idclient="234">
		<lignes>
			<ligne>
				<ref>REF-2234</ref>
				<designation>Pose BA13 (forfait plaque +MO) au m2 </designation>
				<surface unite="m2">15</surface>
				<phtByUnit>9.95</phtByUnit>
				<nbUnit typeUnit="HOURBYMETER2">0.5</nbUnit>
				<stotligne>69.65</stotligne>
			</ligne>
		</lignes>
	</facture>
	<facture numfacture="05" datefacture="2012-06-21" type="facture" idclient="132">
		<lignes>
			<ligne>
				<ref>REF-2234</ref>
				<designation>Pose BA13 (forfait plaque +MO) au m2 </designation>
				<surface unite="m2">15</surface>
				<phtByUnit>9.95</phtByUnit>
				<nbUnit typeUnit="HOURBYMETER2">0.5</nbUnit>
				<stotligne>69.65</stotligne>
			</ligne>
			<ligne>
				<ref>REF-2134</ref>
				<designation>Lavage SOL </designation>
				<phtByUnit>5.95</phtByUnit>
				<nbUnit typeUnit="HOUR">2</nbUnit>
				<stotligne>11.90</stotligne>
			</ligne>
			<ligne>
				<ref>REF-2135-2</ref>
				<designation>Peinture SOL forfait &gt;20m² </designation>
				<phtByUnit>6.95</phtByUnit>
				<nbUnit typeUnit="UNIT">2.5</nbUnit>
				<stotligne>17.375</stotligne>
			</ligne>
		</lignes>
	</facture>

</factures>
